name: Toko Kaset Hilman
version: v1.0.0
port: 3001
debug: true
graphql:
  path: /query
  playground: /__playground
modules:
  mysql:
    host: '127.0.0.1'
    username: 'root'
    password: '12345678'
    database: 'gofar'
  auth:
    model: User
models:
  User:
    username: string `validate:"required,unique"`
    # email: string `db:"unique" validate:"require,unique"`
    # phone: string `db:"unique" validate:"require,unique"`
    password: string `validate:"required,min:10" hide:"true"`
    # role: Role
    __options:
      module_auth: true
  Todo:
    name: string
    description: string
    checked: boolean `db:"default=0"`
    user: User
  # Role:
  #   name: string
  #   slug: string `db:"unique" validate:"require,unique"`
  #   users:
  #     - User
  # Song:
  #   title: string
  #   length: number
  #   band: Band
  #   album: Album
  # Album:
  #   name: string
  #   year: number
  #   band: Band
  #   songs:
  #     - Song
  #   tags:
  #     - string
  # Artist:
  #   name: string
  #   Band: Band
  # Band:
  #   name: string
  #   artists:
  #     - Artist
  #   albums:
  #     - Album
