name: Toko Kaset Hilman
version: v1.0.0
port: 3001
debug: true
graphql:
  path: /query
  playground: /__playground
modules:
  mysql:
    host: '127.0.0.1'
    username: 'root'
    password: '12345678'
    database: 'gofar'
  auth:
    model: User
models:
  User:
    email: string `types:"unique" validate:"require,unique"`
    phone: string `types:"unique" validate:"require,unique"`
    password: string `validate:"require,min:10" hide:"true"`
    role: Role
    __options:
      module_auth: true
  Role:
    name: string
    slug: string `types:"unique" validate:"require,unique"`
    users:
      - User
  Song:
    title: string
    length: number
    band: Band
    album: Album
  Album:
    name: string
    year: number
    band: Band
    songs:
      - Song
    tags:
      - string
  Artist:
    name: string
    Band: Band
  Band:
    name: string
    artists:
      - Artist
    albums:
      - Album
